#!/usr/bin/env bash
# This script manages manage_my_process
pid_path="/var/run/my_process.pid"
if [ "$#" -ne 1 ]
then
  echo "Usage: manage_my_process {start|stop|restart}"
else
  case $1 in
  start)
  ./manage_my_process &
  echo $$ > $pid_path
  echo "manage_my_process started"
  ;;
  stop)
  kill "$(pgrep -f /manage_my_process)"
  rm $pid_path
  echo "manage_my_process stopped"
  ;;
  restart)
  kill "$(pgrep -f /manage_my_process)"
  rm $pid_path
  ./manage_my_process &
  echo $$ > $pid_path
  echo "manage_my_process restarted"
  ;;
  *)
  ;;
  esac
fi
