#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100
fizz="Fizz"
buzz="Buzz"
fizzbuzz="FizzBuzz"
i=1
while [ $i -le 100 ]
do
  if [ $((i % 15)) -le 0 ] ; then
    echo "$fizzbuzz"
  elif [ $((i % 3)) -le 0 ] ; then
    echo "$fizz"
  elif [ $((i % 5)) -le 0 ] ; then
    echo "$buzz"
  else
    echo "$i"
  fi
  i=$((i + 1))
done
