#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes: display hours from 0 to 12, display minutes from 1 to 59
(( i=0 ))
(( j=1 ))
while [ $i -le 12 ]
do
  printf "Hour: %d\\n" "$i"
  while [ $j -le 59 ]
  do
    echo "$j"
    j=$((j + 1))
  done
  i=$((i + 1))
  (( j=1 ))
done
