#!/usr/bin/env bash
# This script is displaying the content of the current directory, in a list format, where only the part of the name after the first dash is displayed
for i in $(find . -type f ! -path "*/.*" | sort)
do
  name=${i:2}
  echo "$name" | cut -d "-" -f 2
done
