#!/usr/bin/env bash
# Uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu
chmod 600 ~/.ssh/school
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/school
ssh -i "~/.ssh/school" "ubuntu@54.144.46.157"
